version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tracker
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+psycopg://tracker:tracker@db:5432/tracker
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker
      POSTGRES_DB: tracker
    depends_on:
      - db
    ports:
      - "8000:8000"

  dashboard:
    build: .
    command: streamlit run dashboard/app.py --server.port=8501 --server.address=0.0.0.0
    environment:
      API_BASE_URL: http://backend:8000
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
    depends_on:
      - backend
    ports:
      - "8501:8501"

volumes:
  pgdata:
