version: "3.9"

services:
  db:
    image: postgres:16
    container_name: creagy_db
    environment:
      POSTGRES_DB: creagy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d creagy"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/creagy
      CORS_ORIGINS: http://localhost:8501,http://dashboard:8501
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    environment:
      API_BASE_URL: http://backend:8000
    depends_on:
      backend:
        condition: service_started
    ports:
      - "8501:8501"

volumes:
  db-data:
